---
kind: Service
apiVersion: v1
metadata:
  name: cloud-hrtable-auth
  labels:
    app: cloud-hrtable-auth
spec:
  selector:
    app: cloud-hrtable-auth
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-hrtable-auth-deployment
  labels:
    app: cloud-hrtable-auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-hrtable-auth
    spec:
      containers:
      - name: samplephp
        image: hrtablekube.azurecr.io/cloudauth:1.0.0
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: cloud.hrtable.com

